/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.manager;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JScrollPane;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.ThongTinCoSoVatChat;
import models.TinhTrangYeuCau;
import controllers.ThongKePanelController;
import controllers.manager.*;
import controllers.manager.nhaVanHoa.CapNhatCoSoVatChat;
import controllers.manager.nhaVanHoa.MainFrameController;
import controllers.manager.nhaVanHoa.ThongTinNguoiDungDangKy;
import controllers.user.XemLichSuDungNhaVanHoaController;
import database.MysqlConnection;


public class MainFrame extends javax.swing.JFrame {

    private MainFrameController controller;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);

        this.controller = new MainFrameController(jTableLich, jTableDonDangKy, jLabelSoDonDKChuaXL, jLabelSoDonDKDaXL, jLabelSoCSVC, jLabelSoCSVCSanCo);
        this.controller.setDataTable();


        
        jComboBoxVatPhamUpdate();
        XemLichSuDung();
        XemThongTinDangKy();
        DefaultTableModel model = (DefaultTableModel) jTableLich.getModel();
        jLabelSoSK.setText(String.valueOf(model.getRowCount()));
        DefaultTableModel model1 = (DefaultTableModel) jTableDonDangKy.getModel();
        jLabelSoDonDK.setText(String.valueOf(model1.getRowCount()));
    }
    
    private void XemLichSuDung(){
        DefaultTableModel model = (DefaultTableModel) jTableLich.getModel();
        XemLich.show(model);
    }
    
    private void XemThongTinDangKy(){
        DefaultTableModel model = (DefaultTableModel) jTableDonDangKy.getModel();
        ThongTinNguoiDungDangKy.print(model);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPanelLeft = new javax.swing.JPanel();
        jPanelTrangChu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelQuanLyCSVC = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelLich = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelDonDangKy = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelDangXuat = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelChuyen = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelQuanLyNVH2 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanelCentre = new javax.swing.JPanel();
        jPanelTrangChuCentre = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelSoDonDK = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabelSoSK = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabelSoDonDKChuaXL = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabelSoDonDKDaXL = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabelSoCSVC = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabelSoCSVCSanCo = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jPanelLichCentre = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLich = new javax.swing.JTable();
        jLabelTenSuKien = new javax.swing.JLabel();
        jLabelThoiGian = new javax.swing.JLabel();
        jLabelPhong = new javax.swing.JLabel();
        jLabelGia = new javax.swing.JLabel();
        jLabelMoTa = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanelDonDangKyCentre = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDonDangKy = new javax.swing.JTable();
        jLabel38 = new javax.swing.JLabel();
        jPanelQuanLyCSVCCentre = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCapNhatCSVC = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxVatPham = new javax.swing.JComboBox<>();
        jButtonChiTiet = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldTTTenVatPham = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldTTSoLuong = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldTTPhong = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldTTNgayCapNhat = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextFieldTT = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxPhong = new javax.swing.JComboBox<>();
        jButtonCapNhat = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelThemCSVC = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldTenVatPham1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jSpinnerSoLuong1 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel21 = new javax.swing.JLabel();
        jButtonXacNhan1 = new javax.swing.JButton();
        jButtonLamMoi1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextFieldTT1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sử dụng nhà văn hóa");

        jPanel.setPreferredSize(new java.awt.Dimension(1500, 800));
        jPanel.setLayout(new java.awt.BorderLayout());

        jPanelLeft.setBackground(new java.awt.Color(32, 107, 166));
        jPanelLeft.setPreferredSize(new java.awt.Dimension(335, 760));

        jPanelTrangChu.setBackground(new java.awt.Color(32, 107, 166));
        jPanelTrangChu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelTrangChu.setPreferredSize(new java.awt.Dimension(185, 60));
        jPanelTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLeftMouseClickedEvt(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-home-48.png"))); // NOI18N
        jLabel1.setText("Trang chủ");
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(225, 225, 225));
        jLabel1.setIconTextGap(10);

        javax.swing.GroupLayout jPanelTrangChuLayout = new javax.swing.GroupLayout(jPanelTrangChu);
        jPanelTrangChu.setLayout(jPanelTrangChuLayout);
        jPanelTrangChuLayout.setHorizontalGroup(
            jPanelTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrangChuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTrangChuLayout.setVerticalGroup(
            jPanelTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrangChuLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelQuanLyCSVC.setBackground(new java.awt.Color(32, 107, 166));
        jPanelQuanLyCSVC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelQuanLyCSVC.setPreferredSize(new java.awt.Dimension(185, 60));
        jPanelQuanLyCSVC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLeftMouseClickedEvt(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/CSVC.png"))); // NOI18N
        jLabel2.setText("Quản lý cơ sở vật chất");
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(225, 225, 225));
        jLabel2.setIconTextGap(10);

        javax.swing.GroupLayout jPanelQuanLyCSVCLayout = new javax.swing.GroupLayout(jPanelQuanLyCSVC);
        jPanelQuanLyCSVC.setLayout(jPanelQuanLyCSVCLayout);
        jPanelQuanLyCSVCLayout.setHorizontalGroup(
            jPanelQuanLyCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyCSVCLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelQuanLyCSVCLayout.setVerticalGroup(
            jPanelQuanLyCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyCSVCLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanelLich.setBackground(new java.awt.Color(32, 107, 166));
        jPanelLich.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelLich.setPreferredSize(new java.awt.Dimension(118, 60));
        jPanelLich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLeftMouseClickedEvt(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Lich.png"))); // NOI18N
        jLabel3.setText("Lịch quản lý sự kiện");
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(225, 225, 225));
        jLabel3.setIconTextGap(10);

        javax.swing.GroupLayout jPanelLichLayout = new javax.swing.GroupLayout(jPanelLich);
        jPanelLich.setLayout(jPanelLichLayout);
        jPanelLichLayout.setHorizontalGroup(
            jPanelLichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLichLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLichLayout.setVerticalGroup(
            jPanelLichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelDonDangKy.setBackground(new java.awt.Color(32, 107, 166));
        jPanelDonDangKy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelDonDangKy.setPreferredSize(new java.awt.Dimension(153, 60));
        jPanelDonDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLeftMouseClickedEvt(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dondangky.png"))); // NOI18N
        jLabel4.setText("Danh sách người đăng ký ");
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(225, 225, 225));
        jLabel4.setIconTextGap(10);

        javax.swing.GroupLayout jPanelDonDangKyLayout = new javax.swing.GroupLayout(jPanelDonDangKy);
        jPanelDonDangKy.setLayout(jPanelDonDangKyLayout);
        jPanelDonDangKyLayout.setHorizontalGroup(
            jPanelDonDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDonDangKyLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDonDangKyLayout.setVerticalGroup(
            jPanelDonDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelDangXuat.setBackground(new java.awt.Color(32, 135, 215));
        jPanelDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelDangXuat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanelDangXuat.setPreferredSize(new java.awt.Dimension(151, 60));
        jPanelDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLeftMouseClickedEvt(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dangxuat.png"))); // NOI18N
        jLabel5.setText("Đăng xuất");
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelDangXuatLayout = new javax.swing.GroupLayout(jPanelDangXuat);
        jPanelDangXuat.setLayout(jPanelDangXuatLayout);
        jPanelDangXuatLayout.setHorizontalGroup(
            jPanelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDangXuatLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanelDangXuatLayout.setVerticalGroup(
            jPanelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanelChuyen.setBackground(new java.awt.Color(32, 107, 166));
        jPanelChuyen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelChuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelChuyenMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/qlgd.png"))); // NOI18N
        jLabel8.setText("Quản lý hộ khẩu");
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(225, 225, 225));
        jLabel8.setIconTextGap(10);

        javax.swing.GroupLayout jPanelChuyenLayout = new javax.swing.GroupLayout(jPanelChuyen);
        jPanelChuyen.setLayout(jPanelChuyenLayout);
        jPanelChuyenLayout.setHorizontalGroup(
            jPanelChuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChuyenLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelChuyenLayout.setVerticalGroup(
            jPanelChuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(32, 107, 166));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("LA KHE");
        jLabel27.setBackground(new java.awt.Color(222, 222, 222));
        jLabel27.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(225, 225, 225));
        jLabel27.setToolTipText("");

        jLabel22.setText("MANAGEMENT");
        jLabel22.setBackground(new java.awt.Color(222, 222, 222));
        jLabel22.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(225, 225, 225));
        jLabel22.setToolTipText("");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(jPanelQuanLyCSVC, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(jPanelLich, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(jPanelDonDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(jPanelChuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanelQuanLyCSVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanelLich, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanelDonDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanelChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jPanel.add(jPanelLeft, java.awt.BorderLayout.LINE_START);

        jPanelQuanLyNVH2.setBackground(new java.awt.Color(32, 135, 215));
        jPanelQuanLyNVH2.setPreferredSize(new java.awt.Dimension(953, 105));

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Quản lý sử dụng nhà văn hóa");
        jLabel33.setAutoscrolls(true);
        jLabel33.setBackground(new java.awt.Color(32, 135, 215));
        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(225, 225, 225));

        jLabel34.setText("PHẠM MINH THỐNG");
        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));

        jLabel35.setText("Tổ trưởng");
        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-avatar-80.png"))); // NOI18N

        javax.swing.GroupLayout jPanelQuanLyNVH2Layout = new javax.swing.GroupLayout(jPanelQuanLyNVH2);
        jPanelQuanLyNVH2.setLayout(jPanelQuanLyNVH2Layout);
        jPanelQuanLyNVH2Layout.setHorizontalGroup(
            jPanelQuanLyNVH2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyNVH2Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelQuanLyNVH2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelQuanLyNVH2Layout.setVerticalGroup(
            jPanelQuanLyNVH2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
            .addGroup(jPanelQuanLyNVH2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelQuanLyNVH2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addGroup(jPanelQuanLyNVH2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCentre.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelCentre.setPreferredSize(new java.awt.Dimension(1169, 800));
        jPanelCentre.setAutoscrolls(true);
        jPanelCentre.setLayout(new java.awt.CardLayout());

        jPanelTrangChuCentre.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTrangChuCentre.setForeground(new java.awt.Color(0, 0, 0));
        jPanelTrangChuCentre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Cập nhật");
        jButton3.setAutoscrolls(true);
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Thêm sự kiện");
        jButton1.setAutoscrolls(true);
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);

        jLabel9.setText("Số đơn đăng kí chưa xử lý:");
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jLabel9);
        jLabel9.setBounds(110, 10, 220, 21);

        jLabelSoDonDK.setText("1000");
        jLabelSoDonDK.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabelSoDonDK.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jLabelSoDonDK);
        jLabelSoDonDK.setBounds(110, 40, 108, 56);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel8);
        jPanel8.setBounds(80, 10, 10, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-form-48.png"))); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 10, 60, 80);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setText("Số sự kiện: ");
        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));

        jLabelSoSK.setText("1000");
        jLabelSoSK.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabelSoSK.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-event-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabelSoSK, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSoSK)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(null);

        jLabel25.setText("Số đơn đăng kí:");
        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jLabel25);
        jLabel25.setBounds(110, 10, 220, 21);

        jLabelSoDonDKChuaXL.setText("1000");
        jLabelSoDonDKChuaXL.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabelSoDonDKChuaXL.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jLabelSoDonDKChuaXL);
        jLabelSoDonDKChuaXL.setBounds(110, 40, 108, 56);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel9);
        jPanel9.setBounds(80, 10, 10, 90);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-form-48.png"))); // NOI18N
        jPanel4.add(jLabel28);
        jLabel28.setBounds(20, 10, 60, 80);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel10.setLayout(null);

        jLabel29.setText("Số đơn đăng kí đã xử lý:");
        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jPanel10.add(jLabel29);
        jLabel29.setBounds(110, 10, 220, 21);

        jLabelSoDonDKDaXL.setText("1000");
        jLabelSoDonDKDaXL.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabelSoDonDKDaXL.setForeground(new java.awt.Color(0, 0, 0));
        jPanel10.add(jLabelSoDonDKDaXL);
        jLabelSoDonDKDaXL.setBounds(110, 40, 108, 56);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel11);
        jPanel11.setBounds(80, 10, 10, 90);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-form-48.png"))); // NOI18N
        jPanel10.add(jLabel30);
        jLabel30.setBounds(20, 10, 60, 80);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel31.setText("Số cơ sở vật chất: ");
        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));

        jLabelSoCSVC.setText("1000");
        jLabelSoCSVC.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabelSoCSVC.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-event-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabelSoCSVC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSoCSVC)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jLabel39.setText("Số phòng chứa cơ sở vật chất: ");
        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));

        jLabelSoCSVCSanCo.setText("1000");
        jLabelSoCSVCSanCo.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabelSoCSVCSanCo.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-event-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(jLabelSoCSVCSanCo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSoCSVCSanCo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout jPanelTrangChuCentreLayout = new javax.swing.GroupLayout(jPanelTrangChuCentre);
        jPanelTrangChuCentre.setLayout(jPanelTrangChuCentreLayout);
        jPanelTrangChuCentreLayout.setHorizontalGroup(
            jPanelTrangChuCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrangChuCentreLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelTrangChuCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTrangChuCentreLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTrangChuCentreLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTrangChuCentreLayout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTrangChuCentreLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanelTrangChuCentreLayout.setVerticalGroup(
            jPanelTrangChuCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrangChuCentreLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelTrangChuCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanelTrangChuCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTrangChuCentreLayout.createSequentialGroup()
                        .addGroup(jPanelTrangChuCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanelTrangChuCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(301, Short.MAX_VALUE))
        );

        jPanelCentre.add(jPanelTrangChuCentre, "card2");

        jPanelLichCentre.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));

        jTableLich = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        jTableLich.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sự kiện", "Thời gian bắt đầu", "Thời gian kết thúc", "Phòng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableLich.setBackground(new java.awt.Color(204, 204, 204));
        jTableLich.setRowHeight(50);
        jTableLich.setToolTipText("");
        jTableLich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLichMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLich);

        jLabelTenSuKien.setText("Tên sự kiện:");
        jLabelTenSuKien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabelThoiGian.setText("Thời gian:");
        jLabelThoiGian.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabelPhong.setText("Phòng:");
        jLabelPhong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabelGia.setText("Giá:");
        jLabelGia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabelMoTa.setText("Mô tả:");
        jLabelMoTa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel37.setText("Lịch sự kiện ");
        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanelLichCentreLayout = new javax.swing.GroupLayout(jPanelLichCentre);
        jPanelLichCentre.setLayout(jPanelLichCentreLayout);
        jPanelLichCentreLayout.setHorizontalGroup(
            jPanelLichCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanelLichCentreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLichCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMoTa)
                    .addComponent(jLabelTenSuKien)
                    .addComponent(jLabelThoiGian)
                    .addComponent(jLabelPhong)
                    .addComponent(jLabelGia)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(549, Short.MAX_VALUE))
        );
        jPanelLichCentreLayout.setVerticalGroup(
            jPanelLichCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLichCentreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTenSuKien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelThoiGian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPhong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMoTa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGia)
                .addGap(105, 105, 105))
        );

        jPanelCentre.add(jPanelLichCentre, "card4");

        jPanelDonDangKyCentre.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTableDonDangKy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên người dùng", "Thời gian bắt đầu", "Thời gian kết thúc", "Phòng", "Mô tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableDonDangKy.setBackground(new java.awt.Color(255, 255, 255));
        jTableDonDangKy.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTableDonDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDonDangKyMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableDonDangKy);

        jLabel38.setText("Danh sách đăng kí ");
        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanelDonDangKyCentreLayout = new javax.swing.GroupLayout(jPanelDonDangKyCentre);
        jPanelDonDangKyCentre.setLayout(jPanelDonDangKyCentreLayout);
        jPanelDonDangKyCentreLayout.setHorizontalGroup(
            jPanelDonDangKyCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1145, Short.MAX_VALUE)
            .addGroup(jPanelDonDangKyCentreLayout.createSequentialGroup()
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelDonDangKyCentreLayout.setVerticalGroup(
            jPanelDonDangKyCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDonDangKyCentreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCentre.add(jPanelDonDangKyCentre, "card5");

        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jPanelCapNhatCSVC.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Chọn vật phẩm:");
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jComboBoxVatPham.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jButtonChiTiet.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonChiTiet.setText("Chi tiết");
        jButtonChiTiet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChiTietActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setText("Tên vật phẩm:");
        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTextFieldTTTenVatPham.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel12.setText("Số lượng:");
        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTextFieldTTSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldTTSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTTSoLuongActionPerformed(evt);
            }
        });

        jLabel13.setText("Phòng:");
        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTextFieldTTPhong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldTTPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTTPhongActionPerformed(evt);
            }
        });

        jLabel15.setText("Thông tin:");
        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel16.setText("Ngày cập nhật: ");
        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTextFieldTTNgayCapNhat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTextFieldTT.setColumns(20);
        jTextFieldTT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldTT.setRows(5);
        jScrollPane4.setViewportView(jTextFieldTT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldTTTenVatPham, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTTPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTTSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTTNgayCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(462, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldTTTenVatPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldTTSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldTTPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldTTNgayCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jLabel10.setText("Thông tin");
        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel14.setText("Phòng:");
        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        XemLichSuDungNhaVanHoaController xemLichSuDungNhaVanHoaController = new XemLichSuDungNhaVanHoaController();
        jComboBoxPhong.setModel(new javax.swing.DefaultComboBoxModel<>(xemLichSuDungNhaVanHoaController.layDanhSachPhong()));
        jComboBoxPhong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPhongActionPerformed(evt);
            }
        });

        jButtonCapNhat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonCapNhat.setText("Cập nhật");
        jButtonCapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCapNhatCSVCLayout = new javax.swing.GroupLayout(jPanelCapNhatCSVC);
        jPanelCapNhatCSVC.setLayout(jPanelCapNhatCSVCLayout);
        jPanelCapNhatCSVCLayout.setHorizontalGroup(
            jPanelCapNhatCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelCapNhatCSVCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCapNhatCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelCapNhatCSVCLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCapNhatCSVCLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCapNhatCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCapNhatCSVCLayout.createSequentialGroup()
                                .addComponent(jButtonChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCapNhat))
                            .addComponent(jComboBoxVatPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(768, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCapNhatCSVCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(525, 525, 525))
        );
        jPanelCapNhatCSVCLayout.setVerticalGroup(
            jPanelCapNhatCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCapNhatCSVCLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelCapNhatCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxVatPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCapNhatCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(27, 27, 27)
                .addGroup(jPanelCapNhatCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonChiTiet)
                    .addComponent(jButtonCapNhat))
                .addGap(61, 61, 61)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab(" Cập nhật cơ sở vật chất", jPanelCapNhatCSVC);

        jPanelThemCSVC.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setText("Chọn phòng:");
        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(xemLichSuDungNhaVanHoaController.layDanhSachPhong()));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel18.setText("Tên vật phẩm:");
        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTextFieldTenVatPham1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel19.setText("Số lượng:");
        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jSpinnerSoLuong1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel20.setText("Thông tin:");
        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        datePicker1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel21.setText("Thời gian:");
        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jButtonXacNhan1.setText("Xác nhận");
        jButtonXacNhan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonXacNhan1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonXacNhan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXacNhan1ActionPerformed(evt);
            }
        });

        jButtonLamMoi1.setText("Làm mới");
        jButtonLamMoi1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLamMoi1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonLamMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLamMoi1ActionPerformed(evt);
            }
        });

        jTextFieldTT1.setColumns(20);
        jTextFieldTT1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldTT1.setRows(5);
        jScrollPane3.setViewportView(jTextFieldTT1);

        javax.swing.GroupLayout jPanelThemCSVCLayout = new javax.swing.GroupLayout(jPanelThemCSVC);
        jPanelThemCSVC.setLayout(jPanelThemCSVCLayout);
        jPanelThemCSVCLayout.setHorizontalGroup(
            jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemCSVCLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(71, 71, 71)
                .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelThemCSVCLayout.createSequentialGroup()
                        .addComponent(jButtonXacNhan1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLamMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelThemCSVCLayout.createSequentialGroup()
                            .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldTenVatPham1)
                                .addComponent(datePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addGap(73, 73, 73)
                            .addComponent(jLabel19)
                            .addGap(31, 31, 31)
                            .addComponent(jSpinnerSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addContainerGap(489, Short.MAX_VALUE))
        );
        jPanelThemCSVCLayout.setVerticalGroup(
            jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemCSVCLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldTenVatPham1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jSpinnerSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonXacNhan1)
                    .addComponent(jButtonLamMoi1))
                .addContainerGap(333, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thêm cơ sở vật chất", jPanelThemCSVC);

        javax.swing.GroupLayout jPanelQuanLyCSVCCentreLayout = new javax.swing.GroupLayout(jPanelQuanLyCSVCCentre);
        jPanelQuanLyCSVCCentre.setLayout(jPanelQuanLyCSVCCentreLayout);
        jPanelQuanLyCSVCCentreLayout.setHorizontalGroup(
            jPanelQuanLyCSVCCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelQuanLyCSVCCentreLayout.setVerticalGroup(
            jPanelQuanLyCSVCCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jPanelCentre.add(jPanelQuanLyCSVCCentre, "card5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelQuanLyNVH2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1165, Short.MAX_VALUE)
            .addComponent(jPanelCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelQuanLyNVH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelCentre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChiTietActionPerformed
        ThongTinCoSoVatChat tt = CapNhatCoSoVatChat.thongTinCoSoVatChat((String)jComboBoxVatPham.getSelectedItem(), (String)jComboBoxPhong.getSelectedItem());
        jTextFieldTTTenVatPham.setText(tt.getItemName());
        jTextFieldTT.setText(tt.getItemDescriptions());
        jTextFieldTTNgayCapNhat.setText(tt.getLastTimeUpDate()); 
        jTextFieldTTPhong.setText(tt.getRoomName());
        jTextFieldTTSoLuong.setText(tt.getAmount() + "");
    }//GEN-LAST:event_jButtonChiTietActionPerformed

    private void jComboBoxPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPhongActionPerformed

        jComboBoxVatPhamUpdate();
    }//GEN-LAST:event_jComboBoxPhongActionPerformed

    private void jButtonCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCapNhatActionPerformed
        new CapNhatCoSoVatChatFrame().setVisible(true);
    }//GEN-LAST:event_jButtonCapNhatActionPerformed

    private void jButtonXacNhan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXacNhan1ActionPerformed
        if(jTextFieldTenVatPham1.getText().length() == 0 || datePicker1.getDate() == null || jTextFieldTT1.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Vui vòng điền đẩy đủ thông tin", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if((int)jSpinnerSoLuong1.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Số lượng phải lớn hơn 0", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        CapNhatCoSoVatChat.themCSVC(jTextFieldTenVatPham1.getText(), (String)jComboBox1.getSelectedItem(), datePicker1.getDate().toString(), jTextFieldTT1.getText(), (int)jSpinnerSoLuong1.getValue());                   
        jComboBoxVatPhamUpdate();
    }//GEN-LAST:event_jButtonXacNhan1ActionPerformed

    private void jButtonLamMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLamMoi1ActionPerformed
        jTextFieldTT1.setText("");
        jTextFieldTenVatPham1.setText("");
        datePicker1.setDate(null);
        jSpinnerSoLuong1.setValue(0);
    }//GEN-LAST:event_jButtonLamMoi1ActionPerformed

    private void jTableLichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLichMouseClicked
        ArrayList<String> arr = XemLich.showDetail((DefaultTableModel)jTableLich.getModel(), jTableLich.getSelectedRow());
        jLabelTenSuKien.setText("Tên sự kiện: " + arr.get(0));
        jLabelThoiGian.setText("Thời gian từ: " + arr.get(1) + " đến: " + arr.get(2));
        jLabelPhong.setText("Phòng: " + arr.get(3));
        jLabelMoTa.setText("Mô tả: " + arr.get(4));
        jLabelGia.setText("Chi Phí: " + arr.get(5) + " đ");
        
                
        
    }//GEN-LAST:event_jTableLichMouseClicked

    private void jTableDonDangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDonDangKyMouseClicked
        new ChapNhanYeuCau((DefaultTableModel) jTableDonDangKy.getModel(), jTableDonDangKy.getSelectedRow()).setVisible(true);
    }//GEN-LAST:event_jTableDonDangKyMouseClicked

    private void jTextFieldTTPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTTPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTTPhongActionPerformed

    private void jTextFieldTTSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTTSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTTSoLuongActionPerformed

    private void jPanelChuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelChuyenMouseClicked

        if(evt.getSource() == jPanelChuyen){
            this.dispose();
            new MainFrame1().setVisible(true);
        }
    }//GEN-LAST:event_jPanelChuyenMouseClicked

    private void jPanelLeftMouseClickedEvt(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLeftMouseClickedEvt
        if(evt.getSource() == jPanelTrangChu){
            jPanelTrangChuCentre.setVisible(true);
            jPanelQuanLyCSVCCentre.setVisible(false);
            jPanelLichCentre.setVisible(false);
            jPanelDonDangKyCentre.setVisible(false);
            DefaultTableModel model = (DefaultTableModel) jTableLich.getModel();
            model.setRowCount(0);
            XemLich.show(model);
            jLabelSoSK.setText(String.valueOf(model.getRowCount()));
            DefaultTableModel model1 = (DefaultTableModel) jTableDonDangKy.getModel();
            model1.setRowCount(0);
            XemThongTinDangKy();
            jLabelSoDonDK.setText(String.valueOf(model1.getRowCount()));
        }
        if(evt.getSource() == jPanelQuanLyCSVC){
            jPanelTrangChuCentre.setVisible(false);
            jPanelQuanLyCSVCCentre.setVisible(true);
            jPanelLichCentre.setVisible(false);
            jPanelDonDangKyCentre.setVisible(false);
        }
        if(evt.getSource() == jPanelLich){
            jPanelTrangChuCentre.setVisible(false);
            jPanelQuanLyCSVCCentre.setVisible(false);
            jPanelLichCentre.setVisible(true);
            jPanelDonDangKyCentre.setVisible(false);
            DefaultTableModel model = (DefaultTableModel) jTableLich.getModel();
            model.setRowCount(0);
            XemLichSuDung();
        }
        if(evt.getSource() == jPanelDonDangKy){
            jPanelTrangChuCentre.setVisible(false);
            jPanelQuanLyCSVCCentre.setVisible(false);
            jPanelLichCentre.setVisible(false);

            jPanelDonDangKyCentre.setVisible(true);
            DefaultTableModel model = (DefaultTableModel) jTableDonDangKy.getModel();
            model.setRowCount(0);
            XemThongTinDangKy();
        }
        if(evt.getSource() == jPanelDangXuat){
            if (JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.dispose();
            new LogInView().setVisible(true);
        } else {

        }
        }
    }//GEN-LAST:event_jPanelLeftMouseClickedEvt

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ThemSuKienFrame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableLich.getModel();
        model.setRowCount(0);
        XemLich.show(model);
        jLabelSoSK.setText(String.valueOf(model.getRowCount()));
        DefaultTableModel model1 = (DefaultTableModel) jTableDonDangKy.getModel();
        model1.setRowCount(0);
        XemThongTinDangKy();
        jLabelSoDonDK.setText(String.valueOf(model1.getRowCount()));
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jComboBoxVatPhamUpdate(){
        jComboBoxVatPham.removeAllItems();
        try{
            Connection conn = MysqlConnection.getMysqlConnection();
            String phong = (String)jComboBoxPhong.getSelectedItem();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from Infrastructure");
             while(rs.next()){
                if(rs.getString("RoomName").equals(phong)){
                    jComboBoxVatPham.addItem(rs.getString("ItemName"));
                }
        }
        } catch(SQLException e){
            
        } catch(ClassNotFoundException e){
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCapNhat;
    private javax.swing.JButton jButtonChiTiet;
    private javax.swing.JButton jButtonLamMoi1;
    private javax.swing.JButton jButtonXacNhan1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxPhong;
    private javax.swing.JComboBox<String> jComboBoxVatPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelGia;
    private javax.swing.JLabel jLabelMoTa;
    private javax.swing.JLabel jLabelPhong;
    private javax.swing.JLabel jLabelSoCSVC;
    private javax.swing.JLabel jLabelSoCSVCSanCo;
    private javax.swing.JLabel jLabelSoDonDK;
    private javax.swing.JLabel jLabelSoDonDKChuaXL;
    private javax.swing.JLabel jLabelSoDonDKDaXL;
    private javax.swing.JLabel jLabelSoSK;
    private javax.swing.JLabel jLabelTenSuKien;
    private javax.swing.JLabel jLabelThoiGian;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelCapNhatCSVC;
    private javax.swing.JPanel jPanelCentre;
    private javax.swing.JPanel jPanelChuyen;
    private javax.swing.JPanel jPanelDangXuat;
    private javax.swing.JPanel jPanelDonDangKy;
    private javax.swing.JPanel jPanelDonDangKyCentre;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelLich;
    private javax.swing.JPanel jPanelLichCentre;
    private javax.swing.JPanel jPanelQuanLyCSVC;
    private javax.swing.JPanel jPanelQuanLyCSVCCentre;
    private javax.swing.JPanel jPanelQuanLyNVH2;
    private javax.swing.JPanel jPanelThemCSVC;
    private javax.swing.JPanel jPanelTrangChu;
    private javax.swing.JPanel jPanelTrangChuCentre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerSoLuong1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDonDangKy;
    private javax.swing.JTable jTableLich;
    private javax.swing.JTextArea jTextFieldTT;
    private javax.swing.JTextArea jTextFieldTT1;
    private javax.swing.JTextField jTextFieldTTNgayCapNhat;
    private javax.swing.JTextField jTextFieldTTPhong;
    private javax.swing.JTextField jTextFieldTTSoLuong;
    private javax.swing.JTextField jTextFieldTTTenVatPham;
    private javax.swing.JTextField jTextFieldTenVatPham1;
    // End of variables declaration//GEN-END:variables
}
